{{- range $i := until (.Values.control_plane.node_count | int) }}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  namespace: {{ $.Values.cluster_namespace }}
  annotations:
    harvesterhci.io/vmRunStrategy: RerunOnFailure
    harvesterhci.io/volumeClaimTemplates: |
      [{"metadata":{"name":"{{ $.Values.cluster_name }}-cp-disk-{{ $i }}","annotations":{"harvesterhci.io/imageId":"{{ $.Values.vm.image_namespace }}/{{ $.Values.vm.image }}"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"{{ $.Values.control_plane.node_disk_gb }}Gi"}},"volumeMode":"Block","storageClassName":"longhorn-ubuntu"}}]
  name: {{ $.Values.cluster_name }}-cp-{{ $i }}
  labels:
    harvesterhci.io/creator: harvester
    harvesterhci.io/os: {{ $.Values.vm.os }}
  finalizers:
    - harvesterhci.io/VMController.UnsetOwnerOfPVCs
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        harvesterhci.io/vmName: {{ $.Values.cluster_name }}-cp-{{ $i }}
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: {{ $.Values.control_plane.cpu_count }}
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: disk-0
            - disk:
                bus: virtio
              name: cloudinitdisk
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
        features:
          acpi:
            enabled: {{ $.Values.vm.uefi_enabled }}
        machine:
          type: q35
        resources:
          limits:
            cpu: {{ $.Values.control_plane.cpu_count }}
            memory: {{ $.Values.control_plane.memory_gb }}Gi
          requests:
            cpu: 125m
            memory: 2730Mi
      evictionStrategy: LiveMigrateIfPossible
      hostname: {{ $.Values.cluster_name }}-cp-{{ $i }}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: {{ $.Values.cluster_name }}-cp-disk-{{ $i }}
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: {{ $.Values.cluster_name }}-cp-{{ $i }}-cloudinit
            networkDataSecretRef:
              name: {{ $.Values.cluster_name }}-cp-{{ $i }}-cloudinit
{{- end }}
