apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    harvesterhci.io/vmRunStrategy: RerunOnFailure
    harvesterhci.io/volumeClaimTemplates: >
      [{"metadata":{"name":"c1-cp-disk-0","annotations":{"harvesterhci.io/imageId":"default/ubuntu"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"40Gi"}},"volumeMode":"Block","storageClassName":"longhorn"}}]
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
    meta.helm.sh/release-name: c1
    meta.helm.sh/release-namespace: default
  creationTimestamp: '2025-03-06T18:13:46Z'
  finalizers:
    - wrangler.cattle.io/VMController.CleanupPVCAndSnapshot
    - kubevirt.io/virtualMachineControllerFinalize
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
    harvesterhci.io/creator: harvester
    harvesterhci.io/os: linux
  managedFields:
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:harvesterhci.io/vmRunStrategy: {}
            f:harvesterhci.io/volumeClaimTemplates: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
            f:harvesterhci.io/creator: {}
            f:harvesterhci.io/os: {}
        f:spec:
          .: {}
          f:runStrategy: {}
          f:template:
            .: {}
            f:metadata:
              .: {}
              f:labels:
                .: {}
                f:harvesterhci.io/vmName: {}
            f:spec:
              .: {}
              f:architecture: {}
              f:domain:
                .: {}
                f:cpu:
                  .: {}
                  f:cores: {}
                  f:sockets: {}
                  f:threads: {}
                f:devices:
                  .: {}
                  f:disks: {}
                  f:inputs: {}
                f:features:
                  .: {}
                  f:acpi:
                    .: {}
                    f:enabled: {}
                f:machine:
                  .: {}
                  f:type: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
              f:evictionStrategy: {}
              f:hostname: {}
              f:networks: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes: {}
      manager: helm
      operation: Update
      time: '2025-03-06T18:13:46Z'
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:kubevirt.io/latest-observed-api-version: {}
            f:kubevirt.io/storage-observed-api-version: {}
          f:finalizers:
            v:"kubevirt.io/virtualMachineControllerFinalize": {}
      manager: virt-controller
      operation: Update
      time: '2025-03-06T18:13:46Z'
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/VMController.CleanupPVCAndSnapshot": {}
        f:spec:
          f:template:
            f:spec:
              f:domain:
                f:devices:
                  f:interfaces: {}
      manager: harvester
      operation: Update
      time: '2025-03-06T18:14:05Z'
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:created: {}
          f:desiredGeneration: {}
          f:observedGeneration: {}
          f:printableStatus: {}
          f:ready: {}
          f:runStrategy: {}
          f:volumeSnapshotStatuses: {}
      manager: virt-controller
      operation: Update
      subresource: status
      time: '2025-03-06T18:14:06Z'
  name: c1-cp-0
  namespace: default
  resourceVersion: '1261164'
  uid: 6cdd55ef-908c-4d5b-87a8-c559654ba866
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      creationTimestamp: null
      labels:
        harvesterhci.io/vmName: c1-cp-0
    spec:
      affinity: {}
      architecture: amd64
      domain:
        cpu:
          cores: 3
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: disk-0
            - disk:
                bus: virtio
              name: cloudinitdisk
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - macAddress: b2:69:3d:5b:36:6b
              masquerade: {}
              model: virtio
              name: default
        features:
          acpi:
            enabled: true
        machine:
          type: q35
        memory:
          guest: 8Gi
        resources:
          limits:
            cpu: '3'
            memory: 8Gi
          requests:
            cpu: 187m
            memory: 5461Mi
      evictionStrategy: LiveMigrateIfPossible
      hostname: c1-cp-0
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 120
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: c1-cp-disk-0
        - cloudInitNoCloud:
            networkDataSecretRef:
              name: c1-cp-0-cloudinit
            secretRef:
              name: c1-cp-0-cloudinit
          name: cloudinitdisk
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2025-03-06T18:14:02Z'
      status: 'True'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: null
      status: 'True'
      type: LiveMigratable
    - lastProbeTime: null
      lastTransitionTime: '2025-03-06T18:14:05Z'
      message: a non-live-updatable field was changed in the template spec
      status: 'True'
      type: RestartRequired
  created: true
  desiredGeneration: 2
  observedGeneration: 2
  printableStatus: Running
  ready: true
  runStrategy: RerunOnFailure
  volumeSnapshotStatuses:
    - enabled: false
      name: disk-0
      reason: 2 matching VolumeSnapshotClasses for longhorn
    - enabled: false
      name: cloudinitdisk
      reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]
