cluster_name: c1
cluster_namespace: default
network_name: vmnet
rke2_version: v1.29.6+rke2r1
ssh_pub_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFUcCNBCR89zztoaHgD1QsdyDYj4pNGWoO0Vnz3KmOaL pressl.alex@imitrix.de"
system_default_registry: ""

control_plane:
  files:
  - content: |
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: cert-manager
        namespace: default      
      spec:
        bootstrap: true
        targetNamespace: cert-manager
        createNamespace: true
        valuesContent: |-
          securityContext:
            runAsNonRoot: true
          crds:
            enabled: true
        version: v1.16.1
        repo: https://charts.jetstack.io
        chart: cert-manager
    owner: root
    path: /var/lib/rancher/rke2/server/manifests/certmanager.yaml
  - content: |
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        name: rancher
        namespace: default      
      spec:
        bootstrap: false
        targetNamespace: cattle-system
        createNamespace: true
        set:
          hostname: rancher.lab.sienarfleet.systems
          replicas: 3
          bootstrapPassword: admin
        valuesContent: |-
          global:
            cattle:
              psp:
                enabled: false
          ingress:
            tls:
              source: rancher
        repo: https://releases.rancher.com/server-charts/stable
        chart: rancher
        version: v2.10.1
    owner: root
    path: /var/lib/rancher/rke2/server/manifests/rancher.yaml
  ipam: static
#  loadbalancer_gateway: 10.0.2.1
#  loadbalancer_subnet: 10.0.2.0/24
  network:
  - |
    network:
      version: 2
      renderer: networkd
      ethernets:
        enp1s0:
          dhcp4: yes
  - |
    network:
      version: 2
      renderer: networkd
      ethernets:
        enp1s0:
          dhcp4: yes
  - |
    network:
      version: 2
      renderer: networkd
      ethernets:
        enp1s0:
          dhcp4: yes
  node_count: 3
#  vip: 10.0.2.20
vm:
  airgapped_image: false
  image_namespace: default        #! namespace in your harvester cluster containing the vm base image
  os: linux
  image: ubuntu
  qemu_agent_enable: true
  qemu_agent_install: true
worker:
  node_count: 0
