apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    harvesterhci.io/vmRunStrategy: RerunOnFailure
    harvesterhci.io/volumeClaimTemplates: >-
      [{"metadata":{"name":"ubuntu-disk-0","annotations":{"harvesterhci.io/imageId":"default/ubuntu"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"volumeMode":"Block","storageClassName":"longhorn-ubuntu"}}]
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"kubevirt.io/v1","kind":"VirtualMachine","metadata":{"annotations":{"harvesterhci.io/vmRunStrategy":"RerunOnFailure","harvesterhci.io/volumeClaimTemplates":"[{\"metadata\":{\"name\":\"ubuntu-disk-0\",\"annotations\":{\"harvesterhci.io/imageId\":\"default/ubuntu\"}},\"spec\":{\"accessModes\":[\"ReadWriteMany\"],\"resources\":{\"requests\":{\"storage\":\"10Gi\"}},\"volumeMode\":\"Block\",\"storageClassName\":\"longhorn-ubuntu\"}}]"},"labels":{"harvesterhci.io/creator":"harvester"},"name":"ubuntu-vm","namespace":"default"},"spec":{"runStrategy":"RerunOnFailure","template":{"metadata":{"annotations":{"harvesterhci.io/sshNames":"[\"default/r1alex\"]"},"labels":{"harvesterhci.io/vmName":"ubuntu-vm"}},"spec":{"architecture":"amd64","domain":{"cpu":{"cores":2,"sockets":1,"threads":1},"devices":{"disks":[{"bootOrder":1,"disk":{"bus":"virtio"},"name":"disk-0"},{"disk":{"bus":"virtio"},"name":"cloudinitdisk"}],"inputs":[{"bus":"usb","name":"tablet","type":"tablet"}],"interfaces":[{"masquerade":{},"model":"virtio","name":"default"}]},"features":{"acpi":{"enabled":true}},"machine":{"type":"q35"},"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"125m","memory":"2730Mi"}}},"evictionStrategy":"LiveMigrateIfPossible","hostname":"ubuntu-vm","networks":[{"name":"default","pod":{}}],"terminationGracePeriodSeconds":120,"volumes":[{"name":"disk-0","persistentVolumeClaim":{"claimName":"ubuntu-disk-0"}},{"cloudInitNoCloud":{"userData":"#cloud-config\npassword:
      ap\nchpasswd: { expire: False }\nssh_pwauth: True\nhostname:
      ubuntu-vm\n"},"name":"cloudinitdisk"}]}}}}
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  creationTimestamp: '2025-03-06T18:16:46Z'
  finalizers:
    - wrangler.cattle.io/VMController.CleanupPVCAndSnapshot
    - kubevirt.io/virtualMachineControllerFinalize
  generation: 2
  labels:
    harvesterhci.io/creator: harvester
  managedFields:
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:harvesterhci.io/vmRunStrategy: {}
            f:harvesterhci.io/volumeClaimTemplates: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:harvesterhci.io/creator: {}
        f:spec:
          .: {}
          f:runStrategy: {}
          f:template:
            .: {}
            f:metadata:
              .: {}
              f:annotations:
                .: {}
                f:harvesterhci.io/sshNames: {}
              f:labels:
                .: {}
                f:harvesterhci.io/vmName: {}
            f:spec:
              .: {}
              f:architecture: {}
              f:domain:
                .: {}
                f:cpu:
                  .: {}
                  f:cores: {}
                  f:sockets: {}
                  f:threads: {}
                f:devices:
                  .: {}
                  f:disks: {}
                  f:inputs: {}
                f:features:
                  .: {}
                  f:acpi:
                    .: {}
                    f:enabled: {}
                f:machine:
                  .: {}
                  f:type: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
              f:evictionStrategy: {}
              f:hostname: {}
              f:networks: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2025-03-06T18:16:46Z'
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:kubevirt.io/latest-observed-api-version: {}
            f:kubevirt.io/storage-observed-api-version: {}
          f:finalizers:
            v:"kubevirt.io/virtualMachineControllerFinalize": {}
      manager: virt-controller
      operation: Update
      time: '2025-03-06T18:16:46Z'
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/VMController.CleanupPVCAndSnapshot": {}
        f:spec:
          f:template:
            f:spec:
              f:domain:
                f:devices:
                  f:interfaces: {}
      manager: harvester
      operation: Update
      time: '2025-03-06T18:17:06Z'
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:created: {}
          f:desiredGeneration: {}
          f:observedGeneration: {}
          f:printableStatus: {}
          f:ready: {}
          f:runStrategy: {}
          f:volumeSnapshotStatuses: {}
      manager: virt-controller
      operation: Update
      subresource: status
      time: '2025-03-06T18:17:06Z'
  name: ubuntu-vm
  namespace: default
  resourceVersion: '1263457'
  uid: 0aa6d56b-f626-4419-90ab-fa4131a235a7
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '["default/r1alex"]'
      creationTimestamp: null
      labels:
        harvesterhci.io/vmName: ubuntu-vm
    spec:
      affinity: {}
      architecture: amd64
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: disk-0
            - disk:
                bus: virtio
              name: cloudinitdisk
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
            - macAddress: 82:52:86:8a:71:68
              masquerade: {}
              model: virtio
              name: default
        features:
          acpi:
            enabled: true
        machine:
          type: q35
        memory:
          guest: 4Gi
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: 125m
            memory: 2730Mi
      evictionStrategy: LiveMigrateIfPossible
      hostname: ubuntu-vm
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 120
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: ubuntu-disk-0
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              password: ap
              chpasswd: { expire: False }
              ssh_pwauth: True
              hostname: ubuntu-vm
          name: cloudinitdisk
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2025-03-06T18:17:03Z'
      status: 'True'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: null
      status: 'True'
      type: LiveMigratable
    - lastProbeTime: null
      lastTransitionTime: '2025-03-06T18:17:06Z'
      message: a non-live-updatable field was changed in the template spec
      status: 'True'
      type: RestartRequired
  created: true
  desiredGeneration: 2
  observedGeneration: 1
  printableStatus: Running
  ready: true
  runStrategy: RerunOnFailure
  volumeSnapshotStatuses:
    - enabled: false
      name: disk-0
      reason: 2 matching VolumeSnapshotClasses for longhorn-ubuntu
    - enabled: false
      name: cloudinitdisk
      reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]
